
import React from 'react'
import styled from 'styled-components'
//

const PageHeader = styled.h1`
  font-weight: 300;
  margin-bottom: 2em;
`

export default () => (
  <div className="grid">
    <PageHeader>Datenschutzerklärung</PageHeader>
    <h4>1. Personenbezogene Daten</h4>
    <h5>1.1 Allgemeines</h5>
    <p>Personenbezogene Daten sind Angaben, die die Identität des Nutzers offenlegen oder offenlegen können. Wir halten uns an den Grundsatz der Datenvermeidung. Es wird soweit wie möglich auf die Erhebung von personenbezogenen Daten verzichtet.</p>
    <h5>1.2 Umgang</h5>
    <p>Personenbezogene Daten dienen ausschließlich der Vertragsbegründung, inhaltlichen Ausgestaltung, Durchführung oder Abwicklung des Vertragsverhältnisses. Sie werden grundsätzlich nicht an Dritte weitergegeben. Lediglich zur Vertragserfüllung werden die Daten an das mit der Lieferung beauftragte Versandunternehmen weitergegeben, soweit dies zur Lieferung bestellter Waren erforderlich ist. Zur Abwicklung von Zahlungen werden die hierfür erforderlichen Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut und ggf. den beauftragten und gewählten Zahlungsdienstleister weitergegeben. Eine Verwendung personenbezogener Daten erfolgt somit nur im notwendigen Umfang oder sofern wir gesetzlich oder per Gerichtsbeschluss dazu verpflichtet wird oder, wenn nötig, um eine gesetzeswidrige oder missbräuchliche Verwendung entgegen den Allgemeinen Geschäftsbedingungen in rechtmäßiger Weise zu unterbinden.</p>
    <h5>1.3 Widerspruch</h5>
    <p>Sie können der Speicherung Ihrer personenbezogenen Daten jederzeit widersprechen. Ausgenommen hiervon sind solche Daten, die zu Zwecken der Vertragsabwicklung bereitgehalten werden müssen.</p>
    <h5>1.4 Auskunftsrecht</h5>
    <p>Auf Anfrage informieren wir Sie über die zu Ihrer Person gespeicherten Daten. Dies erfolgt grundsätzlich kostenlos.</p>
    <h5>1.5 Recht auf Berichtigung, Löschung und Sperrung von Daten</h5>
    <p>Sie haben jederzeit das Recht, unrichtige personenbezogene Daten auf Antrag berichtigen, löschen oder sperren zu lassen. Die Ausübung des Rechts ist kostenlos. </p>
    <h4>2. Nutzungsdaten</h4>
    <p>Beim Besuch der Webseite werden allgemeine technische Informationen erhoben. Hierzu gehören die verwendete IP-Adresse, Uhrzeit, Dauer des Besuchs, Browsertyp und ggf. die Herkunftsseite. Diese Nutzungsdaten werden in einem Logfile registriert und können zum Zwecke der Statistikauswertung dieser Webseite benutzt und gespeichert werden. Eine Verknüpfung dieser Nutzungsdaten mit Ihren personenbezogenen Daten findet nicht statt.</p>
    <h4>3. Datensicherheit</h4>
    <p>Sämtliche Daten auf unserer Website werden durch technische und organisatorische Maßnahmen gegen Verlust, Zerstörung, Zugriff, Veränderung und Verbreitung gesichert. Wir übernehmen jedoch keine Haftung für die Zerstörung und Beschädigung von Daten.</p>
    <h4>4. Sessions und Cookies</h4>
    <p>Zur Bedienung des Internetauftritts können wir Cookies oder serverseitige Sessions einsetzen, in denen Daten gespeichert werden können. Cookies dienen dabei z.B. auch der persönlichen Begrüßung mit dem Mitgliedsnamen. Cookies sind Dateien, die von einer Webseite auf Ihrer Festplatte abgelegt werden, um diesen Computer beim nächsten Webseitenbesuch automatisch wieder zu erkennen und damit die Nutzung der Webseite an Sie anpassen zu können. Einige der verwendeten Cookies werden nach dem Ende der Browser-Sitzung wieder gelöscht. Dabei handelt es sich um sogenannte Sitzungs-Cookies. Andere Cookies verbleiben auf Ihrem Endgerät und ermöglichen die Wiedererkennung des Browsers bei einem späteren Besuch unserer Website (dauerhafte Cookies). Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und einzeln über deren Annahme entscheiden oder die Annahme von Cookies für bestimmte Fälle oder generell ausschließen. Bitte beachten Sie dabei, dass Sie möglicherweise einige Funktionen dieser Website nicht nutzen können, wenn die Cookies deaktiviert sind.</p>
    <h4>5. Dienste von Drittanbietern</h4>
    <h5>5.1 Google Analytics</h5>
    <p>Diese Website benutzt Google Analytics, einen Webanalysedienst von Google, betrieben von der Google Inc.,1600 Amphitheatre Parkway, Mountain View, CA 94043, USA („Google“) und erhebt und speichert über diesen Webanalysedienst Daten, aus denen unter Verwendung von Pseudonymen Nutzungsprofile erstellt werden. Die so erstellten Nutzungsprofile dienen der Auswertung des Besucherverhaltens um das auf dieser Website dargestellte Angebot bedarfsgerecht zu gestalten und zu verbessern. Google Analytics verwendet sog. „Cookies“, kleine Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite, wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Auch die unter einem Pseudonym geführten Nutzungsprofile werden ohne ausdrückliche und gesondert erklärte Einwilligung des Nutzers nicht mit den personenbezogenen Daten über den Nutzer zusammengeführt. Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link (<a href="http://tools.google.com/dlpage/gaoptout?hl=de">http://tools.google.com/dlpage/gaoptout?hl=de </a> ) verfügbare Browser-Plugin herunterladen und installieren.<br></br>
Die Datenschutzhinweise von Google können Sie auf <a href="http://www.google.de/intl/de/policies/privacy/">http://www.google.de/intl/de/policies/privacy/</a> einsehen. Nähere Informationen zu Nutzungsbedingungen und Datenschutz finden Sie unter <a href="http://www.google.com/analytics/terms/de.html">http://www.google.com/analytics/terms/de.html</a> bzw. unter <a href="http://www.google.com/intl/de/analytics/privacyoverview.html">http://www.google.com/intl/de/analytics/privacyoverview.html</a>. Wir weisen Sie darauf hin, dass auf dieser Webseite Google Analytics um den Code „anonymizeIp“ erweitert wurde, um eine anonymisierte Erfassung von IP-Adressen (sog. IP-Masking) zu gewährleisten.</p>
<h5>5.2 Social-Media-Links</h5>
<p>Wir haben bei den über Links von dieser Website zu erreichenden Drittanbietern eigene Social-Media-Seiten. Durch die Nutzung der Links gelangen Sie auf die jeweiligen Internetseiten der Drittanbieter (z.B. Facebook, Twitter, Google+). Sobald Sie die Seite der Drittanbieter aufgerufen haben, befinden Sie sich im Verantwortungsbereich des jeweiligen Drittanbieters, so dass auch deren Datenschutzerklärung bzw. deren Erklärungen zur Datenverwendung gelten. Wir haben hierauf keinen Einfluss, wir empfehlen jedoch zur Vermeidung einer unnötigen Datenweitergabe vor der Nutzung eines entsprechenden Links sich selbst bei dem jeweiligen Drittanbieter auszuloggen, damit nicht schon durch die Verwendung des Links u.U. Nutzungsprofile durch den Drittanbieter erstellt werden können. Wir haben bewusst nur Links eingesetzt und auf weitergehende Plugins der Drittanbieter verzichtet, um Ihre Daten zu schützen.</p>
<h4>6. Kontaktaufnahme</h4>
<p>Zur Kontaktaufnahme bezüglich des Datenschutzes können Sie die im Impressum angegebenen Kontaktmöglichkeiten (z.B. E-Mail) nutzen.</p>
  </div>
)
